(ASC-259) create snapshot from instance
rcbops/molecule-validate-nova-deploy pull request #15
Opened 2018-05-11 22:41 UTC by phongdly

2018-05-11 22:55 UTC, phongdly commented
@johnduarte , the test fails to shutdown newly created instance, I'll look into it on Mon.

2018-05-11 23:13 UTC, johnduarte requested changes

2018-05-11 23:13 UTC, johnduarte commented on molecule/default/tests/utils.py
> +    """Verify if a volume is existing"""
This comment does not seem accurate since any openstack service can be passed in.

2018-05-11 23:13 UTC, johnduarte commented on molecule/default/tests/utils.py
> +def verify_if_exist(service_type, service_name, run_on_host):
This method name seems a bit too ambiguous and doesn't communicate what it does. Is there a better name for it? Perhaps `verify_os_asset_in_list`?

2018-05-11 23:13 UTC, johnduarte commented on molecule/default/tests/utils.py
> +
Please add the expected keys in the `data` dictionary to the doc string.

2018-05-11 23:13 UTC, johnduarte commented on molecule/default/tests/utils.py
> +def shut_it_off(service_type, service_name, run_on_host):
According to [this doc](https://docs.openstack.org/python-openstackclient/latest/cli/decoder.html), the only `openstack` cli subcommand that takes `stop` as an argument is the `server` command. Perhaps this method should not be so general and be explicitly named `stop_server_instance` or something similar.

2018-05-11 23:13 UTC, johnduarte commented on molecule/default/tests/test_create_snapshot_on_instance.py
> +    assert ("available" == utils.get_status_by_name('volume', snapshot_name, host))
I really like this style of assertion. Your helper method really makes the expected result very clear.

2018-05-11 23:13 UTC, johnduarte commented on molecule/default/tests/test_create_snapshot_on_instance.py
> +    utils.create_instance(data_snapshot, host)
I would expect there to be an `assert` after this line to verify that the instance was successfully booted using the snapshot.

2018-05-15 02:20 UTC, johnduarte requested changes

2018-05-15 02:20 UTC, johnduarte commented on molecule/default/tests/test_create_snapshot_on_instance.py
> +    utils.get_expected_status('server', instance_name, "SHUTOFF", 20, host)
I am not crazy about the "magic" 20 value in the middle of this methods parameters. Could you make the retry_count the last argument, give it a default in the method definition and either loose the "magic" value or make it explicit in the call (e.g. `utils.get_expected_status('server, instance_name, 'SHUTOFF', host, retries=20)`)?

2018-05-15 02:20 UTC, johnduarte commented on molecule/default/tests/utils.py
> +    cmd = ". /root/openrc ; nova image-create --poll " \
Is `nova` preferred here over `openstack server image create`?

2018-05-15 15:22 UTC, phongdly commented on molecule/default/tests/utils.py
> +    cmd = ". /root/openrc ; nova image-create --poll " \
Not really, just got it straight from the RPC doc. I'll replace it by openstack cli

2018-05-15 16:49 UTC, phongdly commented
Test passed on Phobos MNAIO:
   ============================= test session starts ==============================
    platform linux2 -- Python 2.7.12, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
    rootdir: /root/github/rpc-openstack-system-tests/molecules/molecule-validate-nova-deploy/molecule/default, inifile:
    plugins: testinfra-1.7.1, rpc-0.6.1
collected 1 item

    tests/test_create_snapshot_on_instance.py .                              [100%]

     generated xml file: /root/github/rpc-openstack-system-tests/molecules/molecule-validate-nova-deploy/molecule/default/molecule_test_results.xml
    ========================== 1 passed in 261.27 seconds ==========================
Verifier completed successfully.

2018-05-15 17:22 UTC, johnduarte approved these changes
![Awesome](https://i.gifer.com/CQJE.gif)

2018-05-15 17:23 UTC, merged