(ASC-228) (ASC-231) reboot infra and cinder hosts
rcbops/molecule-validate-nova-deploy pull request #26
Opened 2018-06-18 16:21 UTC by phongdly

This PR to reboot the infra3, infra2, infra1, and then all cinder hosts in that order, waiting 10 minutes after each reboot and 20 minutes after the last reboot of a cinder host.
TODO: Replace the implicit wait of 10 and 20 minutes after each reboot mentioned above, find a better way to do explicit wait and move on the next step when a certain condition is satisfied, for example all containers in the rebooted host are up and running.

2018-06-18 16:25 UTC, phongdly commented
SSH port 22 on Cinder1 and Cinder2 hosts can never be reached after the reboot, regardless of waiting time. I'll check with @BjoernT and SD team to see if I got the correct reboot order, or some other conditions have to be satisfied before rebooting a next host.

2018-06-18 17:38 UTC, johnduarte requested changes

2018-06-18 17:38 UTC, johnduarte commented on molecule/default/playbook.yml
> +        timeout: 1200
Since these numbers are so large, I think the `sleep` value between checks should be increased (defaults to 1 sec).

2018-06-18 17:38 UTC, johnduarte commented on molecule/default/playbook.yml
> +  hosts: infra3
You can collapse the individual tasks for the `Reboot infra* hosts` tasks by using the `order` directive on the host group to reboot them in reverse order:

```
- name: Reboot os-infra_hosts
  hosts: os-infra_hosts
  order: reverse_inventory
  tasks:
    - shell: sleep 2 && shutdown -r now "Ansible reboot {{ inventory_hostname }} host"
      ...
```

2018-07-26 22:19 UTC, johnduarte approved these changes

2018-07-26 22:19 UTC, merged