(ASC-691) refactored create snapshot test to fix the ci failure
rcbops/molecule-validate-nova-deploy pull request #31
Opened 2018-07-02 20:26 UTC by phongdly

2018-07-02 20:28 UTC, phongdly commented
Verified it passed on phobos mnaio:

--> Executing Testinfra tests found in /root/github/rpc-openstack-system-tests/molecules/molecule-validate-nova-deploy/molecule/default/tests/...
    ============================= test session starts ==============================
    platform linux2 -- Python 2.7.12, pytest-3.6.2, py-1.5.4, pluggy-0.6.0
    rootdir: /root/github/rpc-openstack-system-tests/molecules/molecule-validate-nova-deploy/molecule/default, inifile:
    plugins: testinfra-1.12.0, rpc-0.7.0, ordering-0.5
collected 6 items

    tests/test_create_and_assign_floating_ip.pp ...                           [ 50%]
    tests/test_create_snapshot_on_instance.py ...                            [100%]

     generated xml file: /root/github/rpc-openstack-system-tests/molecules/molecule-validate-nova-deploy/molecule/default/molecule_test_results.xml
    ========================== 6 passed in 345.00 seconds ==========================
Verifier completed successfully.

2018-07-02 22:11 UTC, johnduarte requested changes

2018-07-02 22:11 UTC, johnduarte commented on molecule/default/tests/test_create_snapshot_on_instance.py
> +def test_create_snapshot_on_an_instance(host):
nit pick: I think this should be `test_create_snapshot_of_an_instance`.

2018-07-02 22:11 UTC, johnduarte commented on molecule/default/tests/test_create_snapshot_on_instance.py
> +def test_create_instance_on_snapshot(host):
nit pick: I think this should be `test_create_instance_from_snapshot`

2018-07-03 14:21 UTC, phongdly commented
@johnduarte : updated!

2018-07-03 14:28 UTC, johnduarte approved these changes

2018-07-03 14:28 UTC, merged