(ASC-254) added step to delete server before running nova molecule tests
rcbops/molecule-validate-nova-deploy pull request #35
Opened 2018-07-24 23:08 UTC by phongdly

Prior to this PR, the test box on CI usually has existing servers from the previous tests, this cause the failure of 'no hosts available' when nova molecule tests are trying to create new instances.

This PR to delete all pre-existing servers on the test box before running nova molecule tests.

2018-07-24 23:14 UTC, phongdly commented
Tests passed on mnaio env: https://gist.github.com/phongdly/1f113259a51d43af56cd2ff33371d670

2018-07-24 23:36 UTC, johnduarte commented on tasks/run_openstack_service_setup_playbook.yml
> +- name: Create networks
This is probably a misleading name, since the `openstack-service-setup.yml` playbook sets up much more than just networks.

2018-07-24 23:40 UTC, johnduarte requested changes

2018-07-24 23:40 UTC, johnduarte commented on tasks/run_openstack_service_setup_playbook.yml
> +- name: Create networks
This is probably a misleading name, since the `openstack-service-setup.yml` playbook sets up much more than just networks.

2018-07-25 13:52 UTC, johnduarte approved these changes

2018-07-25 13:52 UTC, merged